import type { Metadata } from 'next';

import './globals.css';

import { Header } from './components/Header';
import { Footer } from './components/Footer';

export const metadata: Metadata = {
    title: 'Powered by NextJS',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='ru'>
            <body>
                <Header />
                <main className='container'>{children}</main>
                <Footer />  
            </body>
        </html>
    );
}
